### ISSUE TITLE
Add Atoms to the sketch library

### ISSUE THREAD

**Issue by devCrossNet** [vuesion/sketch-library#2]
Add the current Atoms to the sketch library and redesign if needed

**Comment by einfalles** [comment]
Hey! There are a few topics we should discuss around spacing, and colors. How should I proceed?

**Comment by devCrossNet** [comment]
@einfalles is it something technical (the way we name or structure things)? or is it just about changing some values?

if it's the second one, just go for it. otherwise, let's chat on slack about it

**Comment by einfalles** [comment]
Going to close this ticket since it's been added in and will take a look at a redesign later!
